### ISSUE TITLE
Issue with scrollbars showing up

### ISSUE THREAD

**Issue by traverse** [fv0/native-ui#11]
I'm having some issues with the scrollbar showing up all the time, I'm experiencing it on my Linux and W7 machines. Tried it with all other packages disabled but that didn't do anything either.

Running Atom 1.1.0 with native-ui 0.8.0 on W7x64 and Elementary OS 0.3.1 Freya (64-bit)

![scrollbar](https://cloud.githubusercontent.com/assets/7240988/11135245/8cbaab80-89a3-11e5-8f25-6ebf5b0f7ded.jpg)
(The scrollbar is like this everywhere not just in the command palette but it was easiest to show)

**Comment by fv0** [comment]
@Traverse I released a fix for this. Can you approve that it now works on Windows? Unfortunately I have no possibility to test it.

**Comment by traverse** [comment]
@fv0 It fixed it for the command palette window but the editor window still has the scrollbar, not sure if that was intended or not?

**Comment by fv0** [comment]
@Traverse Yes, that actually makes sense because without them you would remove a layer of information showing you how many lines the document has. So they'll stay for now.
