### ISSUE TITLE
Linter warning and error colors are difficult to tell apart.

### ISSUE THREAD

**Issue by LuminescentMoon** [fv0/native-ui#16]
http://colorpeek.com/#ff4800,cc0000

Edit for clarification: it's the colors set to the variables [@background-color-warning](https://github.com/fv0/native-ui/blob/master/styles/ui-variables.less#L34) and [@background-color-error](https://github.com/fv0/native-ui/blob/master/styles/ui-variables.less#L35) in [ui-variables.less](https://github.com/fv0/native-ui/blob/master/styles/ui-variables.less).

**Comment by laughedelic** [comment]
+1

**Comment by fv0** [comment]
@Luminess That's a good point. Can you provide a screenshot where I can see the problem more clearly?

**Comment by LuminescentMoon** [comment]
![http://i.imgur.com/PQvhlpS.png](http://i.imgur.com/PQvhlpS.png)

**Comment by fv0** [comment]
@Luminess Thanks. Will include the fix in the next release.

<img width="279" alt="screen shot 2015-11-26 at 09 53 32" src="https://cloud.githubusercontent.com/assets/8401092/11418816/a367d436-9423-11e5-8fac-fad69437a789.png">
