### ISSUE TITLE
weird background on inactive tabs

### ISSUE THREAD

**Issue by teknologist** [fv0/native-ui#18]
Hi,

i was wondering if anyone came across this one. A picture is worth a thousand words.
This happens on OSX El Capitan 10.11.0 and 10.11.1. On a Desktop computer using an NVIDIA card as well as a MacBook Pro. atom version 1.2.3

NOTE: That background patter changes colors every time I restart atom.

![screen shot 2015-11-22 at 18 46 42](https://cloud.githubusercontent.com/assets/148448/11325266/e153615c-9149-11e5-9381-160ee4f2895d.png)

**Comment by fv0** [comment]
@teknologist I've never seen this and can't tell where this background comes from. What other packages have you got installed? I have Atom 1.2.2 installed and everything runs fine.
