### ISSUE TITLE
Incorrect git status for directories

### ISSUE THREAD

**Issue by yo7** [fv0/native-ui#2]
This UI's git status in tree-view is cool, but I have a problem.

If there's a modified file in project, not only the directories including the file but every directories change their icons. It's unexpected behaviour. For example, in the image below, modified file is only an application_controller.rb.

<a href="https://gyazo.com/e127a89820a9ca1623869900173d4de3"><img src="https://i.gyazo.com/e127a89820a9ca1623869900173d4de3.png" /></a>

**Comment by fv0** [comment]
Oh, that shouldn't be of course. Will fix it!
