### ISSUE TITLE
Release notes/Changelog?

### ISSUE THREAD

**Issue by swrobel** [fv0/native-ui#20]
Love the theme - would be nice to know what changes in each version.

**Comment by chriskrycho** [comment]
:+1: Concur, strongly!

**Comment by fv0** [comment]
Thanks for the feedback, @swrobel. Will start doing this with the next release.

**Comment by fv0** [comment]
Started doing this with 3a8faf8dcfd1242f49b630b3ead131fd255df549.

**Comment by swrobel** [comment]
:100:
