### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by fynnit** [fv0/native-ui#21]
are you planning on developing a dark mode, as theres one in El Capitan? (no pressure here :smile:)?

**Comment by net** [comment]
+1

**Comment by fv0** [comment]
Yes, I already started working on a dark theme but then some other issues occured with the light theme. When the light theme has reached a version where you and I can't find any serious bugs anymore, then I will fork the theme and adapt it. All I can say is that the dark tone will slightly adapt to your used syntax theme background color (similar to the default _One Dark_ theme from Atom).

**Comment by fynnit** [comment]
awesome. looking forward to that!

Ferdinand schrieb:

**Comment by blimmer** [comment]
+1 - really like the native look and feel but it was too bright for me.

**Comment by marcgalloway** [comment]
+1 - I liked it overall but a dark theme would be better.  Looking forward to it!

**Comment by benjamin-rood** [comment]
+1 for the brooding mysterious stranger theme ;-)
Seriously, I just want it to blend better with the dark ui theme of El Capitan and the fact that I mostly code on a dark background.

**Comment by papucho** [comment]
+1 Great!

**Comment by seemethere** [comment]
+1 I would love a dark theme

**Comment by vieko** [comment]
+1 awesome work so far, looking forward to your Dark UI

**Comment by hex** [comment]
+1

**Comment by mattchue** [comment]
+1, love the current version, a dark theme would be even better.

**Comment by apemsel** [comment]
+1, would love to see that since I enjoy the level of integration with OSX but light grey bars are a bit distracting with dark syntax themes

**Comment by nonameolsson** [comment]
+1

**Comment by heinst** [comment]
👍 , any update on this?

**Comment by fv0** [comment]
@heinst There's a early beta on my machine, but it's not ready for a release yet. I'm working on it… side projects take their time :)

**Comment by heinst** [comment]
Sweet thanks! @fv0

**Comment by mckennajones** [comment]
@fv0 Any updates on this? Is there anyway we could gain access to the beta to test it out and maybe help with development? Loving the theme, but it's a bit distracting when using a dark syntax theme.

**Comment by fv0** [comment]
Dear @mckennajones, no progress yet. I'm kneedeep into my Bachelor thesis for a couple of months. Finished at the end of this month luckily! Thanks for the offer, I'd love to release an early version and get feedback from you guys. I realize this is a heavily requested version of NativeUI. Thanks for the patience!

**Comment by heinst** [comment]
Any other news @fv0 ? Its been a while :/

**Comment by marcelhadorn** [comment]
+1
Will have to wait to use it till there's a dark theme, since I can't read filenames of certain filetypes with file-color package enabled. I'm quiet used to browsing filetypes after color, so I rather won't disable that package. ;)

It would be also nice, if "dark" doesn't just mean "black" but rather inherits the color of the syntax-theme 😉

**Comment by gugadev** [comment]
+1 @fv0 Do you have plans to release it in a short-middle term?

PS: any PayPal or another payment method for donations?

**Comment by fv0** [comment]
@gugadev I’ve gotten around to some experiments but nothing I’d ship as a beta yet. Thanks for offering donations, but I am not in need of it at the moment. Invite someone for a beer and tell them about the theme :-)

**Comment by rolzing** [comment]
+1 DARK THEMEE

**Comment by chriskrycho** [comment]
Given Mojave's recent release, I'm here to check in on the status. I *may* be able to help with it after the start of the year (though I wouldn't count on it 😬); but I would definitely love it.

**Comment by heinst** [comment]
I hate to break it to everyone but this issue was create 3 years ago...i think its safe to say its never coming 🤷‍♂️

**Comment by fv0** [comment]
**Hey everyone**

I wanted to give you and update on how it is going with the dark mode. It’s not that I don’t want it, but I want it to be equally as good as the light interface.
I created a “walking skeleton” prototype to try around if I can make the interface dark and match the syntax theme colors.

![image](https://user-images.githubusercontent.com/8401092/49325141-bd261580-f53d-11e8-94ba-3f4d6b141bf0.png)

![image](https://user-images.githubusercontent.com/8401092/49325160-fcecfd00-f53d-11e8-905b-118192163539.png)


Some question that remain unanswered, which I would like to get your help on.

- Can context menus automatically use the dark theme, when applied in the system settings? So far the interface is dark, but the “right-click-menu” is still light. The same applies to the windows title bar.
  - How do you do this in Electron? Is Atom going to ship it out of the box?
- Should the interface adapt to the syntax colors or just stay dark with no color hue?
  - I’m going towards a dark gray with no color hue, so the dark context menus fit in well and it feels more like other macOS applications would look like. Like Finder for example.
  - This would mean that if you have a dark syntax theme, it might mean that the syntax’ background color won’t contrast well with the surrounding interface elements of Native UI.

Overall I haven’t come to a satisfying result yet, that’s why I didn’t ship it yet. Rather don’t ship something that have something that comprimises overall product quality and makes maintenance super complicated.

What are your thoughts on my proposed questions, how do you view this? Thank you for your active participation and for caring what I put out many years ago as a theme I was missing myself :-)

**Comment by TheTourer** [comment]
> Can context menus automatically use the dark theme, when applied in the system settings? So far the interface is dark, but the “right-click-menu” is still light. The same applies to the windows title bar.

Yes, with Mojave's Dark Mode enabled, the context menus take on the dark styling automatically, system wide. I don't think there'll be a way for Electron to choose/enforce which styling is used independent of the OS, if I had to guess. Maybe look into a way to detect the current mode and display the theme variant based on that? I know there are some other Atom packages that allow theme switching based on it, so they have to be accessing some form of exposed system API to get that info.

> I’m going towards a dark gray with no color hue, so the dark context menus fit in well and it feels more like other macOS applications would look like. Like Finder for example.

I think this is the correct approach to stay as beautifully native as possible. The light theme is a perfect 1:1 reflection of the rest of the OS styling, so why shouldn't the dark version be? There are a bunch of syntax-adaptive themes out there already, but not any that perfectly mimic Mojave's dark styling colors and other UI styling bits.

> This would mean that if you have a dark syntax theme, it might mean that the syntax’ background color won’t contrast well with the surrounding interface elements of Native UI.

Users can/should choose a fitting syntax theme for the app theme, or edit the background color of an existing one not to clash. If anything, maybe make syntax adaptation a default-off setting?

I really appreciate the work you're doing on this, and the patient, quality-assuring way you're doing it. Cheers! 🍻 Thank _YOU_!

EDIT: added screenshot of what the context menu looks like in Dark Mode over a dark syntax theme, for reference

![screen shot 2018-12-11 at 11 45 37 am](https://user-images.githubusercontent.com/867611/49815729-6d63fd00-fd3a-11e8-9c61-5f44837b1dc7.png)

**Comment by swrobel** [comment]
I'd just like to say I agree w/ @TheTourer on the fact that the default (or perhaps only) behavior is that the theme should reflect the native dark mode colors, just light light mode. I use light mode syntax themes with yellowish backgrounds like solarized and it doesn't bother me, so I don't see why dark mode should behave any differently.

Any updates on your thinking, @fv0?

**Comment by KyNorthstar** [comment]
I would love to see this realized. Catalina will come out this September, marking a full year of stable-channel macOS having dark mode support. Absolutely would love to use this theme along with that.

**Comment by fv0** [comment]
I’ve been watching this thread for a while now. I’ve pretty much moved to Visual Studio Code for my coding work, that’s why nothing happened on this theme here anymore.

I’d like to quote [Bastian Allgeier](https://twitter.com/bastianallgeier/status/1169875855738167296) about his take on dark themes.

> […] The amount of work that would need to go into this and the added maintenance effort is just not worth it. In the end it’s nothing more than a design gimmick for a few fans if you ask me.

Instead of making false promises and keeping people waiting forever, I’d rather take a stance and say that **I don’t see a dark theme coming for Native UI**. I had a separate branch existing where I tried getting everything right that you can switch between both modes and have the same experience. But fact is: you can’t just invert all colors and then you’ve got dark mode. There are so many nuances to watch for that I simply gave up on it.

**But…** the context menus on the other hand should adapt to the system settings, I just haven’t found out how to do that yet. Maybe this isn’t a setting for the theme, but for Electron? Feel free to contact me if you know how to solve this.
