### ISSUE TITLE
Border bottom radius on popup window when no description.

### ISSUE THREAD

**Issue by jordwalke** [fv0/native-ui#22]
![screen shot 2015-12-02 at 4 08 30 pm](https://cloud.githubusercontent.com/assets/977348/11548239/218cabc6-990f-11e5-90a4-217394cb2d4c.png)

I believe you wanted some rounding on the bottom radius when there's no description, right?

**Comment by fv0** [comment]
Yes, that's right. Will look into this.

**Comment by Teggy** [comment]
Hi all,

one unrelated question (my apologies für hijacking this issue): What would be the name of the font in the screenshot above?

Thanks and cheers,
  —Torsten

**Comment by fv0** [comment]
@Teggy: Guessing my typographic eye, I'd say that is [PragmataPro](http://www.fsd.it/fonts/pragmatapro.htm#.US2yeBmGYS8).

Can you confirm that, @jordwalke?

**Comment by jordwalke** [comment]
Yes.

**Comment by jordwalke** [comment]
Worth every penny.
