### ISSUE TITLE
Git modified file names look bad in the titlebar

### ISSUE THREAD

**Issue by ghost** [fv0/native-ui#23]
When a file has been modified in a git repo, the filename in the tab bar changes color based on the change. Eg. yellow when the file has changed and green when the file is new. This looks absolutely terrible on the top tab bar since there is no contrast at all.

<img width="380" alt="screen shot 2015-12-10 at 7 49 46 pm" src="https://cloud.githubusercontent.com/assets/13653918/11717547/3e6992fe-9f77-11e5-814a-2fcf11b7c363.png">

<img width="379" alt="screen shot 2015-12-10 at 7 50 06 pm" src="https://cloud.githubusercontent.com/assets/13653918/11717548/3fcca55a-9f77-11e5-9bf6-c3e6d4b5ada4.png">

**Comment by fv0** [comment]
Have you got any plugins installed that do this? This file in my Git repository has been modified and looks like this in my tab bar:

<img width="440" alt="screen shot 2015-12-11 at 15 37 48" src="https://cloud.githubusercontent.com/assets/8401092/11746230/4484fcf4-a01d-11e5-97b6-6135eedff50f.png">

**Comment by aniforprez** [comment]
Ok same guy different account.

This is exactly what someone on another theme account told me 'How does it color the name?'.

It's actually the core tabs plugin! It's got an option that allows coloring of VCS edited files. Just go to tabs > Settings > Enable VCS Coloring

**Comment by fv0** [comment]
Thanks for clearing that up. I can just recommend to deactivate this option until I find a good solution for this. 

<img width="1006" alt="screen shot 2015-12-15 at 10 08 27" src="https://cloud.githubusercontent.com/assets/8401092/11806538/139d93cc-a314-11e5-8b72-200b6da6c6d0.png">

**Comment by ghost** [comment]
I don’t think I’ll deactivate a feature I find very useful but I know that you need time if you are trying to fix this and it is a very minor visual issue that does not impact any actual coding so I can live with it.

**Comment by fv0** [comment]
The current fix might change a bit in the future since I am not 100% satisfied with the understability of so many different colored circles. I'm maybe thinking about a small "M" badge for modified files and a "+" badge for added files. Similar to the file displays in the Git client _Tower_. 

<img width="252" alt="screen shot 2015-12-18 at 17 46 45" src="https://cloud.githubusercontent.com/assets/8401092/11902067/9594d910-a5af-11e5-86b2-35d4138aa5cd.png">

**Comment by ghost** [comment]
Hey that's really good. I also love the idea of M for modified and + for
new ones.

**Comment by aniforprez** [comment]
Awesome. There's some difficulty in simply glancing and finding out the status when the tab stretches across the whole tab bar when there is only one file open because the indicator is in the far right but it will definitely do the job and looks better than the ugly coloring it used to be.
