### ISSUE TITLE
Sidebar improvements

### ISSUE THREAD

**Issue by ricardoaugusto** [fv0/native-ui#25]
Sidebar should behave the same as tabs, when notifying about changes/edits/new files.

<img width="431" alt="screen shot 2015-12-10 at 5 52 12 pm" src="https://cloud.githubusercontent.com/assets/7663281/11726651/cc3420f6-9f66-11e5-9ea1-8a7d9bb8f3b8.png">

<img width="188" alt="screen shot 2015-12-10 at 5 52 01 pm" src="https://cloud.githubusercontent.com/assets/7663281/11726647/c6af4a84-9f66-11e5-8b60-f2bf0467589a.png">

<img width="196" alt="screen shot 2015-12-10 at 5 48 02 pm" src="https://cloud.githubusercontent.com/assets/7663281/11726633/ae092fd6-9f66-11e5-9b12-b3ca462891d5.png">

What could work, at least for me:
- tabs with filled circles, text in black
- sidebar with filled circles next to name, text in black

**Comment by ricardoaugusto** [comment]
Related #23

**Comment by fv0** [comment]
@ricardoaugusto For now I recommend you disable the VCS coloring in the settings of the "tabs" package ([See here](https://github.com/fv0/native-ui/issues/23#issuecomment-164694843)). The sidebar should usually show different colored and filled circles for the Git status of the file. Have you got [file-icons](https://atom.io/packages/file-icons) installed?

<img width="230" alt="screen shot 2015-12-15 at 10 15 53" src="https://cloud.githubusercontent.com/assets/8401092/11806655/da1e9dde-a314-11e5-840a-4b793dce05bc.png">
