### ISSUE TITLE
Minimap selected items are not easily visible

### ISSUE THREAD

**Issue by ghost** [fv0/native-ui#26]
![screen shot 2015-12-14 at 3 17 56 pm](https://cloud.githubusercontent.com/assets/13653918/11777667/e42efe12-a275-11e5-8de2-8283f140124f.png)

The selected items on the minimap (using package minimap-highlight-selected) are very dim in color (since they're completely black) and are hence not easily distinguished. The currently selected item is even less distinguishable since it's a weird grey color and blends too well with the darker syntax themes.

**Comment by fv0** [comment]
I didn't do any modifications to this. But you can adjust it in your user stylesheet according to [the packages README file](https://atom.io/packages/minimap-highlight-selected):

```
/* The rule for normal highlights */
.minimap .highlight-selected {
  background: blue;
}

/* The rule for selected highlights */
.minimap .highlight-selected.selected {
  background: red;
}
```
