### ISSUE TITLE
Unable to click/scroll in palette

### ISSUE THREAD

**Issue by mgoodness** [fv0/native-ui#27]
I'm unable to scroll through or click on items in the Command Palette. Nor can I click on dialog buttons (e.g. Git Plus: Unstage files). Scrolling has no effect, and clicking simply dismisses the palette/dialog. I can only use the keyboard to interact. Everything seems to work correctly with other UI themes.

Using native-ui v0.10.0 on Atom v1.3.1 in El Capitan

Happy to help troubleshoot. Any ideas on where to start?

**Comment by lexicalunit** [comment]
I'm also seeing this behavior on Atom 1.4.0-beta1, OS X El Capitan.
