### ISSUE TITLE
Strong border on tabs

### ISSUE THREAD

**Issue by natew** [fv0/native-ui#28]
This looks different from the screens in the repo for me, is it a bug?

![image](https://cloud.githubusercontent.com/assets/12100/11847032/4cfaf562-a3d0-11e5-98e4-2287f6bfdbae.png)

**Comment by fv0** [comment]
Are you using a high-resolution display? I don't really see a bug here though… The widths are always 1 pixel.

**Comment by natew** [comment]
Hm yea I guess it's the shadow that casts upwards.

![image](https://cloud.githubusercontent.com/assets/12100/11906687/50b56386-a583-11e5-887b-147a05b0e32b.png)

Shouldn't that 1px not exist? It prevents the theme from looking truly native.

Also when inactive the tabs should also go inactive I think:

![image](https://cloud.githubusercontent.com/assets/12100/11906696/6747dd68-a583-11e5-8ada-27f34dc1f882.png)

**Comment by fv0** [comment]
Are you using the latest version (0.11.0)? This is what it looks like in my editor.

<img width="733" alt="screen shot 2015-12-21 at 15 52 23" src="https://cloud.githubusercontent.com/assets/8401092/11933242/fc2fe352-a7fa-11e5-9c94-5220bbe8f9f9.png">

**Comment by natew** [comment]
Yea see that looks fantastic! I want that! I had just downloaded it when I opened the ticket. I can try again on this new computer I have here though. 

Also would we have to campaign Atom themselves to try and allow getting rid of that last pixel? Would make a big difference.
