### ISSUE TITLE
ugly scroll bar

### ISSUE THREAD

**Issue by xiaoxinghu** [fv0/native-ui#36]
I don't know if this is an issue or not. If not, please close this. I got very ugly scroll bar by using a dark syntax theme with the native-ui.

<img width="502" alt="screenshot 2016-01-09 15 17 29" src="https://cloud.githubusercontent.com/assets/1196745/12213800/320443d6-b6e4-11e5-8ddc-9ed312970b0c.png">

**Comment by fv0** [comment]
Hey Xiaoxing, if your hardware allows it, I can recommend using the following settings in your **System Preferences** → **General**: 

<img width="412" alt="screen shot 2016-01-09 at 09 35 30" src="https://cloud.githubusercontent.com/assets/8401092/12215236/5d2d6644-b6b4-11e5-9fd6-53bdd171042b.png">

The scrollbars should then be gone. If you have them always visible this will be the outcome and I won't try to manipulate them with the various -webkit scrollbar hacks that exist out there.

**Comment by nomoon** [comment]
Unfortunately, Logitech USB mice (maybe all USB mice) seem to cause these bars to always appear, even when the "Automatic" setting is selected.

I'll try a mighty mouse tonight.
