### ISSUE TITLE
Line between tree-view and editor vanishes

### ISSUE THREAD

**Issue by lexicalunit** [fv0/native-ui#39]
Not sure if this is intentional or not, but when a file name extends beyond the width of the tree view, the hard line between it and the editor vanishes:

![out](https://cloud.githubusercontent.com/assets/1903876/12455547/be81a2c4-bf61-11e5-8016-64487c5f1538.gif)

**Comment by fv0** [comment]
@lexicalunit I uploaded a potential fix in the latest version. Can you approve that it works for you?

**Comment by lexicalunit** [comment]
Confirmed, I can't recreate this bug on version 0.14.0 :+1:
