### ISSUE TITLE
package.json file icon out of place

### ISSUE THREAD

**Issue by acstll** [fv0/native-ui#42]
Hi there, first of all thank you for your work on this theme.

This could be a bug but I'm not sure. The icon for the package.json is out of place, below where it should be. Other `.json` icons show up ok. If I switch to other themes, it shows ok too, this only happens while using `native-ui`.

Any ideas?

![](http://arturu.com/ruleta/native-ui-them-bug.png)

**Comment by fv0** [comment]
Yes, there are some custom styles for some icons of the package _file-icons_. The error was that the icon didn't look for the scope selector of [file-icons](https://atom.io/packages/file-icons). So if you install this package everything should look fine. The top margin was done to align it properly with the file name (see image).

<img width="240" alt="screen shot 2016-01-25 at 10 57 54" src="https://cloud.githubusercontent.com/assets/8401092/12547786/85a61238-c352-11e5-8708-a802b0245097.png">

I just released a fix for this, please update. It will now only apply the styles, if _file-icons_ is installed.

**Comment by acstll** [comment]
Now I get it, I'm not using file-icons. Will update then (as usual :smile:). Thanks a lot.
