### ISSUE TITLE
Too big font of the interface

### ISSUE THREAD

**Issue by laughedelic** [fv0/native-ui#43]
I'm not sure if this is related to this theme or just the [Ensime plugin](https://github.com/ensime/ensime-atom) that I'm using, because I didn't use it for some time (also lately this theme was updated frequently). So I'd like @hedefalk also to see it.

Here you can see that the font of the Ensime output window is way too big. But also the font of the settings page it quite big comparing to the other interface elements (tabs and the tree-view). I think it wasn't like this before.
<img width="1280" alt="screen shot 2016-01-29 at 15 20 11" src="https://cloud.githubusercontent.com/assets/766656/12677914/5cc022da-c69c-11e5-890e-9e556461a486.png">

**Comment by hedefalk** [comment]
This is definitely Ensime:

https://github.com/hedefalk/ensime-atom/blame/master/styles/ensime.less#L41-L42

I think it was intentional. We'll have to ask @d6y - we're 2 against 1 that the font is too big, mind if we make it smaller? :)

**Comment by d6y** [comment]
Wow - that looks huge. Sure - go for it! Thanks.

**Comment by fv0** [comment]
Could you move the discussion over the ensime package? I'll close this for now :)
