### ISSUE TITLE
Unable to see new replaced icon on Mac

### ISSUE THREAD

**Issue by planetpratik** [fv0/native-ui#44]
Hello Ferdinand, I am using OS X El Capitan. I've downloaded Atom.icns from the link in the description of theme, And replaced it in the "Resources" folder as shown below.

<img width="786" alt="1" src="https://cloud.githubusercontent.com/assets/12500760/12700889/2e0887c2-c81b-11e5-8723-668d784999fc.png">

Then i've restarted Mac & found out that, Atom icon is no more visible. Please check the 2 photos below.

<img width="516" alt="2" src="https://cloud.githubusercontent.com/assets/12500760/12700903/b975fd12-c81b-11e5-8ed7-f56b09ce2ee4.png">

<img width="583" alt="3" src="https://cloud.githubusercontent.com/assets/12500760/12700908/e84e9842-c81b-11e5-9672-7c8565b91a2f.png">

Please let me know the solution for this issue. Also, what about file.icns ? I've kept it as it is.. but does it need to be replaced by new one  ( if any ? ) I haven't found any link regarding updated file.icns in the theme description.

Thank You.

**Comment by fv0** [comment]
This isn't an issue with the icon, it's the process of how to change an icon on OSX El Capitan. Take a look at [this how-to guide](http://hashbangstar.net/blog/changing-icons-in-el-capitan). Just copying it in the `Resources` folder didn't work for me either.

**Comment by planetpratik** [comment]
Thanks man.. It solved the issue..! 

Sent from my iPhone

**Comment by juni0r** [comment]
The icon change doesn't survive Atom updates however. I guess there is no way around this, is there?

**Comment by fv0** [comment]
@juni0r Nope, that's not an issue with the icon but with Atom.
