### ISSUE TITLE
Hide tab bar if only one file open

### ISSUE THREAD

**Issue by leo** [fv0/native-ui#47]
I don't now what's the best way to do this (probably using JS), but it seems like a great idea to me to simply hide the tab bar as long as only one tab is open. We simply don't need to show it since the top bar already includes the path/name of the current file.

![Screenshot](https://cloud.githubusercontent.com/assets/6170607/13147847/e1528c36-d65a-11e5-98e3-ab051cfe1f84.png)

Like all native windows that support tabs do it:
- **Terminal:** [Before](https://cloud.githubusercontent.com/assets/6170607/13147932/4dad5cb2-d65b-11e5-8041-ecc00183e9fa.png), [After](https://cloud.githubusercontent.com/assets/6170607/13147933/4dd9d7c4-d65b-11e5-8095-c9356ed9ed9a.png) 
- **Safari:** [Before](https://cloud.githubusercontent.com/assets/6170607/13147986/99d96414-d65b-11e5-811c-e2d8c9b72af2.png), [After](https://cloud.githubusercontent.com/assets/6170607/13147985/99aec74a-d65b-11e5-8bd6-ac08784784b8.png)
- **Finder:** [Before](https://cloud.githubusercontent.com/assets/6170607/13148090/0bb8aacc-d65c-11e5-9005-eee3fb6633e5.png), [After](https://cloud.githubusercontent.com/assets/6170607/13148047/e6003192-d65b-11e5-97cd-e2649b2b871d.png)

**Comment by fv0** [comment]
If it's possible to do it without adding extra weight to the theme with JS, I think it's a good idea. I don't want to sacrifice speed for aesthetics.

**Comment by jamesplease** [comment]
Is this fixed as of 0.18.0? If so, the issue can prob be closed :v:

**Comment by leo** [comment]
I looks like @fv0 simply removed the code because it spawned an issue (instead of modifying it to make it work)... 😄 So the feature currently isn't part of the package.

**Comment by jamesplease** [comment]
Ah okay, gotcha!

**Comment by fv0** [comment]
@jmeas Yes, after implementing this the issue #55 occured. I haven't put the time in to figure it out why it broke things for people.

**Comment by jamesplease** [comment]
Npnp :v:

**Comment by gabrie30** [comment]
Would it be possible, instead of hiding the tab bar, to keep the maximum length to something smaller. Like how sublime does it.
<img width="600" alt="screen shot 2017-06-24 at 2 14 23 pm" src="https://user-images.githubusercontent.com/1512282/27511990-91ae2ecc-58e7-11e7-8b21-64bac259da89.png">

**Comment by fv0** [comment]
> @gabrie30: Would it be possible, instead of hiding the tab bar, to keep the maximum length to something smaller. Like how sublime does it.

Yes that would be possible, but since Native UI tries to simulate a macOS experience it wouldn’t fit. I’d like to add a little option menu to the theme where the tab sizing could be turned from flexible width to fixed with, but I don’t know how to do create this menu.

Maybe someone has experience with this and knows how to set this up? Feel free to get in touch and we’ll make it happen for Native UI :-)

**Comment by leo** [comment]
Closing this now, as I don't have a need for it anymore. Thanks everyone! 😊
