### ISSUE TITLE
Atom-panel.modal::before positioned absolute, making elements within the modal unreachable.

### ISSUE THREAD

**Issue by krisis-nl** [fv0/native-ui#48]
When I tried to use this theme together with the package [project-viewer](https://github.com/jccguimaraes/atom-project-viewer) I noticed [something weird](https://github.com/jccguimaraes/atom-project-viewer/issues/30) happening with content in the modal panels. 

As I found out, a styled `::before` element of the modal itself, which is positioned absolute, prevents the user from accessing certain elements within the modal. I get this was done for design purposes, but forces themes to give a `position: relative` on their own container holding the modal content. 

If you could possibly change this, your theme might be more compatible with other packages now and in the future.

**Comment by mfunkie** [comment]
Maybe even just adding `z-index: -1` would help out a ton.

**Comment by fv0** [comment]
@dakrisis Does the problem still exist after updating to the newest version?
