### ISSUE TITLE
Love the theme, but...

### ISSUE THREAD

**Issue by sbromberger** [fv0/native-ui#51]
Is it possible to change the font used in the settings input boxes? ~~I don't know what's being used but~~ it's way too wide for my tastes. (Screenshot attached.)

<img width="614" alt="screen shot 2016-03-19 at 10 00 27" src="https://cloud.githubusercontent.com/assets/941359/13900021/80435b8e-edb9-11e5-96b0-cacc86074c94.png">

(Edit: it looks like it may be whatever's used in the Atom editor windows - in my case, Source Code Pro - which works well by itself but doesn't look great mixed with narrower / non-fixed-width fonts.)

**Comment by fv0** [comment]
Yes, that's right. This is Atoms default behaviour. If you change it in your editor it changes in the input fields. System monospace fonts are mostly ugly and I don't want to enforce this. If you want to change this you could of course do this in your user stylesheet (**Atom** → **Stylesheet**).

**Comment by sbromberger** [comment]
The Unity UI has a different font (Helv?) for input boxes regardless of the editor window font. Is there a font setting for just the settings input boxes?
