### ISSUE TITLE
Search and replace bar shorter?

### ISSUE THREAD

**Issue by dahjelle** [fv0/native-ui#53]
Love your theme—thank you!

I was curious if it would be possible to make a more vertically-compact find-and-replace panel at the bottom? (Is that even part of a theme's responsibility?) I usually don't search for long strings, so most of the find/replace boxes are left white, and I'd love to have some vertical space back.

Thoughts?

**Comment by fv0** [comment]
I'm glad that you like my theme. Of course I could build a myriad of options and customization options for Native UI but that would mean giving up control over the design. You can tweak this in your Atom custom stylesheet.
