### ISSUE TITLE
Status bar covers the Tree View pane

### ISSUE THREAD

**Issue by samirotiv** [fv0/native-ui#57]
Hi,
The screenshots show that the status bar needs to stop short of tree view. But this doesn't seem to be working on Atom 1.8.0 and the version of the plugin installed a few minutes back.

Attaching a screenshot.

Best regards,
Samir.
![screen shot 2016-07-06 at 1 52 36 pm](https://cloud.githubusercontent.com/assets/4405935/16611781/16dbc08c-4381-11e6-8ad1-cf3c3d8fbc70.png)

**Comment by fv0** [comment]
I can't tell a lot from your screenshot. Here it works just fine. Can you give me some more information? You're the first one to report this.

![screen shot 2016-07-07 at 11 17 57](https://cloud.githubusercontent.com/assets/8401092/16648471/864ba992-4434-11e6-96a3-6b88a91482c9.png)

**Comment by jamesplease** [comment]
I'm seeing what's in the original issue, rather than what's in your screenshot, @fv0. It's been this way for awhile now. Here's a snippet:

![image](https://cloud.githubusercontent.com/assets/2322305/17469653/041c9d54-5cea-11e6-9970-ff7c30e95b63.png)

Not too sure what could cause this difference, though. Maybe either you or the two of us have a setting configured that causes this different behavior?

**Update:**

I tried changing it to other themes. The status bar still spans the whole width of the bottom of the editor for me, rather than stopped at the edge of the tree view. The screenshot on the Atom editor homepage displays the same layout as your screenshot, @fv0 . So it seems likely that it's some setting or plugin that's causing the issue for us.

**Update 2:**

The HTML structure of my editor doesn't suggest that it's even built with what you're seeing in mind, @fv0 . Check out this GIF:

![gif](https://cldup.com/iyDIipw7zf.gif)

I'd be curious to see the HTML structure of your editor, @fv0 .

Also, you can also see that a top border exists on the status bar when the content pane (the stuff that isn't DevTools) is not in focus. It disappears when I click into the pane to give it focus.

**Update 3:**

I deleted the Atom app and reinstalled a fresh one. It seemed to keep all of my preferences around, though, so it didn't help :P

I also checked my work computer. It's also having this issue.

I originally set up Atom on this computer sometime last year (2015). The work computer is new-ish; set up in Feb of this year.

**Comment by fv0** [comment]
@jmeas What version of Atom do you have? There have been some changes to Atom and the current version of the theme makes it look like this for me. I haven’t updated the screenshots yet, thats why it looks a bit different in the status bar.

Atom 1.9.6.
Native UI 0.18.3

![screen shot 2016-08-08 at 07 27 25](https://cloud.githubusercontent.com/assets/8401092/17470065/a68e5d08-5d39-11e6-8e05-e1bcad41df49.png)

<details>
 <summary>

My installed packages</summary>



```
Built-in Atom Packages (89)
├── about@1.5.2
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.0
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.41.0
├── bracket-matcher@0.82.1
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.38.3
├── find-and-replace@0.198.0
├── fuzzy-finder@1.3.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.1
├── image-view@0.58.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── language-c@0.52.1
├── language-clojure@0.21.0
├── language-coffee-script@0.47.0
├── language-csharp@0.12.1
├── language-css@0.36.2
├── language-gfm@0.86.0
├── language-git@0.13.0
├── language-go@0.42.0
├── language-html@0.44.1
├── language-hyperlink@0.16.0
├── language-java@0.22.0
├── language-javascript@0.119.0
├── language-json@0.18.0
├── language-less@0.29.3
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.35.0
├── language-php@0.37.0
├── language-property-list@0.8.0
├── language-python@0.45.0
├── language-ruby@0.68.5
├── language-ruby-on-rails@0.25.0
├── language-sass@0.52.0
├── language-shellscript@0.22.3
├── language-source@0.9.0
├── language-sql@0.21.1
├── language-text@0.7.1
├── language-todo@0.28.0
├── language-toml@0.18.0
├── language-xml@0.34.8
├── language-yaml@0.26.0
├── line-ending-selector@0.5.0
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.64.1
├── one-dark-syntax@1.2.0
├── one-dark-ui@1.3.2
├── one-light-syntax@1.2.0
├── one-light-ui@1.3.2
├── open-on-github@1.2.0
├── package-generator@1.0.0
├── settings-view@0.238.0
├── snippets@1.0.2
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── spell-check@0.67.1
├── status-bar@1.4.1
├── styleguide@0.46.0
├── symbols-view@0.113.0
├── tabs@0.98.0
├── timecop@0.33.1
├── tree-view@0.208.0
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.32.2
└── wrap-guide@0.38.1

Community Packages (18)
├── atom-typescript@10.1.6
├── atom-wrap-in-tag@0.6.0
├── autocomplete-paths@1.0.2
├── double-tag@0.2.0
├── file-icons@1.7.18
├── highlight-selected@0.11.2
├── language-jade@0.7.1
├── linter@1.11.15
├── linter-jshint@2.1.0
├── linter-jsonlint@1.3.0
├── minimap@4.24.7
├── native-dark-ui@0.6.1
├── native-ui@0.18.3
├── open-terminal-here@2.1.4
├── pigments@0.31.2
├── project-manager@2.9.7
├── tidy-markdown@3.0.1
└── zentabs@0.8.7
```

</details>

**Comment by jamesplease** [comment]
Both of my computers have the latest versions of every package (and Atom). To be more explicit, they're both using the same version of Atom (1.9.6) and Native UI (0.18.3) that you are.

Did you run some command to generate that nice list of packages, or is there a way to export the list in that format?

**Comment by fv0** [comment]
@jmeas Yes, go to your terminal. If you have the Atom Package Manager installed you can type `apm list` and then just copy the output.

**Comment by jamesplease** [comment]
Thanks @fv0 . Here's my list:

<details>
  <summary>

Installed packages (Click to expand)</summary>



```
Built-in Atom Packages (89)
├── about@1.5.2
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.0
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.41.0
├── bracket-matcher@0.82.1
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.38.3
├── find-and-replace@0.198.0
├── fuzzy-finder@1.3.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.1
├── image-view@0.58.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── language-c@0.52.1
├── language-clojure@0.21.0
├── language-coffee-script@0.47.0
├── language-csharp@0.12.1
├── language-css@0.36.2
├── language-gfm@0.86.0
├── language-git@0.13.0
├── language-go@0.42.0
├── language-html@0.44.1
├── language-hyperlink@0.16.0
├── language-java@0.22.0
├── language-javascript@0.119.0
├── language-json@0.18.0
├── language-less@0.29.3
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.35.0
├── language-php@0.37.0
├── language-property-list@0.8.0
├── language-python@0.45.0
├── language-ruby@0.68.5
├── language-ruby-on-rails@0.25.0
├── language-sass@0.52.0
├── language-shellscript@0.22.3
├── language-source@0.9.0
├── language-sql@0.21.1
├── language-text@0.7.1
├── language-todo@0.28.0
├── language-toml@0.18.0
├── language-xml@0.34.8
├── language-yaml@0.26.0
├── line-ending-selector@0.5.0
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.64.1
├── one-dark-syntax@1.2.0
├── one-dark-ui@1.3.2
├── one-light-syntax@1.2.0
├── one-light-ui@1.3.2
├── open-on-github@1.2.0
├── package-generator@1.0.0
├── settings-view@0.238.0
├── snippets@1.0.2
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── spell-check@0.67.1
├── status-bar@1.4.1
├── styleguide@0.46.0
├── symbols-view@0.113.0
├── tabs@0.98.0
├── timecop@0.33.1
├── tree-view@0.208.0
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.32.2
└── wrap-guide@0.38.1

Community Packages (11) /Users/jmeas/.atom/packages
├── Stylus@3.0.0
├── atom-postcss-inline-comments@1.0.0
├── editorconfig@1.4.1
├── emmet@2.4.3
├── language-actionscript@0.2.0
├── language-javascript-jsx@0.3.7
├── language-json-comments@0.16.3
├── language-latex@0.6.1
├── language-postcss@1.2.3
├── native-ui@0.18.3
└── open-in-browser@0.4.7
```

</details>

I tried disabling every community package that I have, and rebooted Atom, and that didn't seem to help.

@fv0, if you open up DevTools, what's the HTML structure of the status bar/tree view look like?

**Comment by fv0** [comment]
> if you open up DevTools, what's the HTML structure of the status bar/tree view look like?

Do you want to see the code that it displays to me? What information do you need? :-) Unfortunately I wasn’t able to reproduce the error.

**Comment by jamesplease** [comment]
@fv0 i posted a gif above of the html in my editor that's responsible for what i'm seeing. a similar gif or screenshot of that section of your editor could be helpful.
