### ISSUE TITLE
system font missing in sierra

### ISSUE THREAD

**Issue by sndrs** [fv0/native-ui#60]
it looks like the `font-family` name needs to be `BlinkMacSystemFont` now?

not sure what it would be for headlines...

**Comment by fv0** [comment]
Can you provide a screenshot?

**Comment by sndrs** [comment]
i'm using a temporary overide in my global `styles.less` file, but this is the tab and nav bar without the override:

![screen shot 2016-09-12 at 12 10 12](https://cloud.githubusercontent.com/assets/867233/18433941/36919a64-78e2-11e6-997e-07cfcc6b805e.png)
![screen shot 2016-09-12 at 12 10 24](https://cloud.githubusercontent.com/assets/867233/18433946/3af1fc02-78e2-11e6-9252-88c50e57489a.png)

and the nav bar with it:

![screen shot 2016-09-12 at 12 10 36](https://cloud.githubusercontent.com/assets/867233/18433951/435d7934-78e2-11e6-86fb-12abd4785e9f.png)

the computed styles without the override on the tab is 

```
'.SFNSText-Regular', 'San Francisco Text', 'Lucida Grande', 'Segoe UI', Ubuntu, Cantarell, sans-serif
```

**Comment by fv0** [comment]
Thanks. I’ll have to find out how this behaves for the headings, because the characters are a bit more dense in that font style.

**Comment by fv0** [comment]
@sndrs Can you confirm that the new version fixes your issue?

**Comment by sndrs** [comment]
yep, looks great :)

:+1:
