### ISSUE TITLE
Atom v1.13.0: Deprecated selector in `native-ui/index.less`

### ISSUE THREAD

**Issue by int3h** [fv0/native-ui#61]
As of Atom v1.13.0, `atom-text-editor` elements no longer use the shadow DOM. See atom/atom#12903 for details.

Accordingly, in Atom `1.13.0-beta0`, Deprecation Cop spits out the following warnings for the `native-ui` package. While Atom v1.13.0 tries to automatically fix the selectors by dynamically rewriting them, there appear to still be bugs with native-ui (I've specifically noticed modal popups, like the command palette, have missing/incorrect borders, among other things.)

So, I'm filing the auto-suggested issue from Depreciation Cop so that native-ui can be updated 😃 

For the record, this is my output from the `atom-beta --versions` command:
```
Atom    : 1.13.0-beta0
Electron: 1.3.6
Chrome  : 52.0.2743.82
Node    : 6.3.0
```

---

In `native-ui/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor[mini] .cursor,
atom-text-editor[mini]::shadow .cursor` => `atom-text-editor[mini] .cursor,
atom-text-editor[mini].editor .cursor`

* `.command-palette atom-text-editor[mini] .cursor,
.fuzzy-finder atom-text-editor[mini] .cursor,
.symbols-view atom-text-editor[mini] .cursor,
.grammar-selector atom-text-editor[mini] .cursor,
.encoding-selector atom-text-editor[mini] .cursor,
.command-palette atom-text-editor[mini] .cursor,
.fuzzy-finder atom-text-editor[mini] .cursor,
.symbols-view atom-text-editor[mini] .cursor,
.grammar-selector atom-text-editor[mini] .cursor,
.encoding-selector atom-text-editor[mini] .cursor,
.command-palette atom-text-editor[mini]::shadow .cursor,
.fuzzy-finder atom-text-editor[mini]::shadow .cursor,
.symbols-view atom-text-editor[mini]::shadow .cursor,
.grammar-selector atom-text-editor[mini]::shadow .cursor,
.encoding-selector atom-text-editor[mini]::shadow .cursor,
.command-palette atom-text-editor[mini]::shadow .cursor,
.fuzzy-finder atom-text-editor[mini]::shadow .cursor,
.symbols-view atom-text-editor[mini]::shadow .cursor,
.grammar-selector atom-text-editor[mini]::shadow .cursor,
.encoding-selector atom-text-editor[mini]::shadow .cursor` => `.command-palette atom-text-editor[mini] .cursor,
.fuzzy-finder atom-text-editor[mini] .cursor,
.symbols-view atom-text-editor[mini] .cursor,
.grammar-selector atom-text-editor[mini] .cursor,
.encoding-selector atom-text-editor[mini] .cursor,
.command-palette atom-text-editor[mini] .cursor,
.fuzzy-finder atom-text-editor[mini] .cursor,
.symbols-view atom-text-editor[mini] .cursor,
.grammar-selector atom-text-editor[mini] .cursor,
.encoding-selector atom-text-editor[mini] .cursor,
.command-palette atom-text-editor[mini].editor .cursor,
.fuzzy-finder atom-text-editor[mini].editor .cursor,
.symbols-view atom-text-editor[mini].editor .cursor,
.grammar-selector atom-text-editor[mini].editor .cursor,
.encoding-selector atom-text-editor[mini].editor .cursor,
.command-palette atom-text-editor[mini].editor .cursor,
.fuzzy-finder atom-text-editor[mini].editor .cursor,
.symbols-view atom-text-editor[mini].editor .cursor,
.grammar-selector atom-text-editor[mini].editor .cursor,
.encoding-selector atom-text-editor[mini].editor .cursor`

* `atom-text-editor[mini],
atom-text-editor[mini]::shadow` => `atom-text-editor[mini],
atom-text-editor[mini].editor`

* `atom-text-editor[mini] .cursor,
atom-text-editor[mini]::shadow .cursor` => `atom-text-editor[mini] .cursor,
atom-text-editor[mini].editor .cursor`

* `atom-text-editor[mini] .selection .region,
atom-text-editor[mini]::shadow .selection .region` => `atom-text-editor[mini] .selection .region,
atom-text-editor[mini].editor .selection .region`

* `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini]::shadow .placeholder-text` => `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini].editor .placeholder-text`

* `atom-text-editor[mini].is-focused,
atom-text-editor[mini].is-focused::shadow` => `atom-text-editor[mini].is-focused,
atom-text-editor[mini].is-focused.editor`

* `atom-text-editor[mini].is-focused .placeholder-text,
atom-text-editor[mini].is-focused::shadow .placeholder-text` => `atom-text-editor[mini].is-focused .placeholder-text,
atom-text-editor[mini].is-focused.editor .placeholder-text`

* `atom-text-editor[mini].is-focused .selection .region,
atom-text-editor[mini].is-focused::shadow .selection .region` => `atom-text-editor[mini].is-focused .selection .region,
atom-text-editor[mini].is-focused.editor .selection .region`

* `.settings-view .section atom-text-editor[mini],
.settings-view .section atom-text-editor[mini]::shadow` => `.settings-view .section atom-text-editor[mini],
.settings-view .section atom-text-editor[mini].editor`

* `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini]::shadow .placeholder-text` => `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini].editor .placeholder-text`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by fv0** [comment]
Wow, thanks for the heads-up, Matt. 

I got it working in 1.13.0-beta3 but now of course the stable version is all messed up, since it still relies on the `atom-text-editor[mini]` selector. Any thoughts on how to get compatibility in both versions without releasing two different packages? I guess not everyone will update to 1.13.0 immediately when it’s released as a stable version. Many will just see a broken theme and wonder what’s going on.

**Comment by fv0** [comment]
Fixed with newest release. Updates will only be applied to Atom versions >1.13.0. You can define this in your `package.json` file.
