### ISSUE TITLE
Problem with platformio-ide-terminal

### ISSUE THREAD

**Issue by pietrodn** [fv0/native-ui#63]
I'm using the native-ui theme together with the platformio-ide-terminal plugin. The problem is that the buttons of the plugin overlap with the name of the currently opened file.
![schermata 2017-02-12 alle 12 01 59](https://cloud.githubusercontent.com/assets/5058646/22861538/9239466c-f11b-11e6-845f-96eff4c4f36e.png)

**Comment by fv0** [comment]
Could you provide a screenshot that is a bit more detailed?

**Comment by pietrodn** [comment]
Sure!
![schermata 2017-02-12 alle 19 33 17](https://cloud.githubusercontent.com/assets/5058646/22864916/3ebdc6b8-f15a-11e6-84a0-67c3a9d045aa.png)

**Comment by pietrodn** [comment]
Related issue (and fix): https://github.com/platformio/platformio-atom-ide-terminal/issues/166

**Comment by ghost** [comment]
@fv0 I've opened up a PR to resolve the styling conflict with the `platformio-ide-terminal` package.

**Comment by laughedelic** [comment]
This seems to be solved now

**Comment by pietrodn** [comment]
Yes, it's fixed in the other plugin.
