### ISSUE TITLE
Project search results malformed

### ISSUE THREAD

**Issue by DanFreed** [fv0/native-ui#67]
I love the look of the theme, but the search results are oddly malformed.  

You can see in the screenshot that the display doesn't always show the results within the file.  The blue highlight under the first filename should be a list of lines that contains the search results.

Scrolling through the results shows many examples of this.  
![screenshot_77](https://cloud.githubusercontent.com/assets/7361751/24527611/8cd23a5a-1568-11e7-80c8-0b531c1f1bdf.png)

Switching the UI theme to something like Unity I can see them again:

![screenshot_78](https://cloud.githubusercontent.com/assets/7361751/24527690/ecfac7b2-1568-11e7-98fd-03b3aaeff895.png)

My styles.less has the following (if it matters):

.tree-view {

}

.editor {

}

.editor .cursor {

}

@import "packages/file-icons/styles/colours";

.octicon-package {
  content: "\f0c4"
}
.icon-file-directory {
    &[data-name=".git"]:before {
        font-family: Devicons;
        content: "\E602";
    }
}

**Comment by fv0** [comment]
Hey @DanFreed 

Your `styles.less` file looks fine, I don’t see any interference here. Maybe it’s best you open the Developer Tools in Atom and inspect the container of a single search result to see if there is some kind of plugin giving your a negative margin-bottom or something like that. You’re the first one to file this issue and it looks fine on my side.

**Comment by laughedelic** [comment]
I have the same issue and I don't have any custom styles defined.

**Comment by fv0** [comment]
> I have the same issue and I don't have any custom styles defined.

@laughedelic: Could you maybe too inspect the search results with the developer tools and see what’s making them overlap? It’s hard to diagnose this without knowing if there’s some kind of plugin interfering.

**Comment by MikeNGarrett** [comment]
Suffering from the same issue. 

It looks like the calculated vertical position of these elements is incorrect. 
![screen shot 2017-04-13 at 11 50 21 am](https://cloud.githubusercontent.com/assets/394888/25012748/6ebdc8f4-203f-11e7-8860-3ae3ee7e5be5.png)

By the way, everything worked well since your last update. It was the latest update of Atom that broke search results styling.

**Comment by dmo-odoo** [comment]
This bug affects me too ! I don't know how Atom search results used to work before, but now their position is computed using position:absolute and setting the top value, and it seems this computation is giving wrong results with respect to your theme.

**Comment by fv0** [comment]
I had to change the design of the search results. When I had a bit of distance between the search results it doesn’t compute the height of the results correctly anymore, which makes them overlap. This was introduced with 1.16 and this is the way we’ll have to roll until I find a work around. But it think it’s still more clear as the standard display of results.

Check the [`README.md`](https://github.com/fv0/native-ui/blob/master/README.md) to see a screenshot of how they look now.
