### ISSUE TITLE
Broken styling for linter-status-count (linter v2)

### ISSUE THREAD

**Issue by UrsaDK** [fv0/native-ui#68]
It appears that with the release of linter version 2, html for the status counter has been updated and the counter now looks like this:

<img width="235" alt="broken" src="https://cloud.githubusercontent.com/assets/2833247/24829269/528beb34-1c66-11e7-9f4c-4acdd181a12a.png">

The following code updates the look of the counter to something a little bit more palatable: 

<img width="184" alt="fixed" src="https://cloud.githubusercontent.com/assets/2833247/24829272/5db72e24-1c66-11e7-9700-74567e51cbf6.png">

```
status-bar {
    .linter-status-count {
        background-color: darken(@btn-base-color, 65%);
        border-radius: @border-radius--base;

        span[class^=highlight] {
            border-radius: 0;
        }
        .highlight {
            background-color: inherit;
            color: @text-color-selected;
        }

        &:hover {
            background-color: darken(@btn-base-color, 65%) !important;
        }
    }
}
```

**Comment by fv0** [comment]
This was implemented in the latest release. @UmkaDK, thanks for your proposal.
