### ISSUE TITLE
Heads up: find in project is showing incomplete/incorrect results in 1.18.0 beta

### ISSUE THREAD

**Issue by sbromberger** [fv0/native-ui#70]
Hi,

Please ref: https://github.com/atom/find-and-replace/issues/896, specifically https://github.com/atom/find-and-replace/issues/896#issuecomment-301950247.

Summary is that "Find in Project" results are not correct when this theme (version 0.20.6) is enabled. Switching themes resolves the issue.

(I realize that beta support may be spotty, but I figure I'd give you a heads up anyway.)

This is on OSX 10.12.4.

**Comment by sbromberger** [comment]
Possibly related to #67?

**Comment by DanFreed** [comment]
I can confirm this behavior as well.  It looks like it is an "off by one" issue. It always shows 1 less line in the results than there actually are.

**Comment by swrobel** [comment]
I'm seeing it as well in 1.17.2

**Comment by DanFreed** [comment]
Anyone know how to patch the theme at least temporarily until an actual fix is released?

**Comment by TheTourer** [comment]
Getting this as well. Troublingly, when there's only a single result per file, nothing shows at all, making the view effectively useless—can't action on anything that would open the file.

**Comment by fv0** [comment]
> @DanFreed: Anyone know how to patch the theme at least temporarily until an actual fix is released?

You can edit the theme and comment out the `project-find-results.less` file in `index.less`. This will put it back to its default state. I’m working on a fix at the moment though.

**Comment by sbromberger** [comment]
Thank you, @fv0! testing now.

**Comment by TheTourer** [comment]
Works again! Thanks so much @fv0; this theme makes Atom look like it should on macOS. It's the gold standard for native themes.
