### ISSUE TITLE
[Option] Tree View Vibrancy

### ISSUE THREAD

**Issue by the0neyouseek** [fv0/native-ui#72]
Now that Atom `1.19` is out, could we have an option to turn on vibrancy for the tree view ?

The `Javascript` api is as folllow :

```js
// Options :
// 1. 'medium-light'
// 2. 'light'
// 3. 'dark'
// 4. 'ultra-dark'
// 5. null (to remove vibrancy)
require('electron').remote.getCurrentWindow().setVibrancy('light');
```

For it to work the tree view and html element must have a transparent background like so (*I did this quickly so this can probably be improved*)  :

```css
html,
atom-workspace,
.atom-dock-mask,
.pane,
.tree-view {
	background: transparent !important;
}
```

**Comment by fv0** [comment]
@the0neyouseek Very cool idea! I tried to emulate this with a slight gradient, but it was of course “faking” the real transparency effect. Do you know where and how would I implement the Javascript for Native UI?

**Comment by the0neyouseek** [comment]
Have a look at [atom/one-light-ui](https://github.com/atom/one-light-ui) for example.

You need to define : 
- A `configSchema` in [`package.json`](https://github.com/atom/one-light-ui/blob/master/package.json#L20)
- A  [`main`](https://github.com/atom/one-light-ui/blob/master/package.json#L13) js/coffee file to handle the different state (see [`lib/main.coffee`](https://github.com/atom/one-light-ui/blob/master/lib/main.coffee))

**Comment by fv0** [comment]
@the0neyouseek: I’d love to see this happen. My knowledge as a Designer is a bit limited in this case, could you help out and create a merge request for this feature? You can leave it in a basic state, I’d do the finetuning from there. From what you write you already got it working on your machine?

**Comment by the0neyouseek** [comment]
Yeah sure no problem. I'll do it and make a pull request.
PS. If you want a temporary solution to see the result right now you can add the css to your `Atom` stylesheet which you can find in the menu <kbd>Atom</kbd>&gt;<kbd>Stylesheet…</kbd> and the script to your init script in <kbd>Atom</kbd>&gt;<kbd>Init Script…</kbd>

**Comment by fv0** [comment]
With my Init Script I get the message

```
Failed to load /Users/fv/.atom/init.coffee
require(...).remote.getWindow is not a function
```

But I think you’ll figure it out :-)

**Comment by the0neyouseek** [comment]
Oops. It was `getCurrentWindow()` not `getWindow()` 😅. I've edited m'y first comment too

**Comment by fv0** [comment]
Do you have an idea how we could solve the display of an active file with CSS or JS-magic? Like in Apple Mail for example. Seems to be a reduced transparency only in that area.

![screen shot 2017-08-10 at 22 00 37](https://user-images.githubusercontent.com/8401092/29189588-6882aa3c-7e17-11e7-8302-8888eafd781e.png)

**Comment by the0neyouseek** [comment]
Sadly, Atom only allow the whole window to have vibrancy...  
So to achieve this effect youd've have to set the window the the "*active*" vibrancy, set the selected tree view item background to `transparent` and cover up the rest of the tree view with a white transparent mask to emulate a lighter blur, like `rgba(255, 255, 255, 0.3)` for example.  
You can't just set the whole tree view to this color though because the parent of the selected item must be transparent since it's the whole window who's got vibrancy on it. Only the tree view parts above and below the selected item need to be color filled. 

I've managed to get a nice look with this stylesheet :

```css
.tree-view .entry:before {
    background: rgba(255, 255, 255, 0.3);
    height: 24px;
    left: 0;
    right : 0;
}

.tree-view .selected:before {
    background: transparent;
}
```

**Comment by laughedelic** [comment]
I updated it and restarted Atom, but I don't see this effect. How do I turn it on?
