### ISSUE TITLE
Not sure the result I have is expected

### ISSUE THREAD

**Issue by dmo-odoo** [fv0/native-ui#73]
Hello,

I was just prompted to update native-ui, here is the result:
![screen shot 2017-08-14 at 08 22 06](https://user-images.githubusercontent.com/8427726/29260377-ca5a145c-80c9-11e7-990e-878274fa35cb.png)

It doesn't look very good (compared to before I updated the package, which looked like the screenshots in the readme of the repo), and I'm wondering if it's the intended look or if something is amiss.

Please note that I'm using the no-title-bar package as well, since it may be a conflict between those two. However, I think using both those packages really enhances the experience on MacOS.

Thank you,
David

**Comment by fv0** [comment]
Hey David, are you on Atom 1.19? What happens if you deactivate the no-titlebar package?

**Comment by dmo-odoo** [comment]
Hello,

Thank you for your reply. It looks better with the no-titlebar package disabled.
![screen shot 2017-08-14 at 09 17 31](https://user-images.githubusercontent.com/8427726/29261752-7edc7030-80d1-11e7-9222-0afa2b1707c0.png)

Not sure what to do now.

**Comment by fv0** [comment]
Don’t know if this makes it better, but Atom can hide the titlebar natively. You don’t need a package for that. Just go to <kbd>Settings</kbd> → <kbd>Core</kbd> and set **Title bar** to **Hidden**.

<img width="816" alt="screen shot 2017-08-14 at 09 55 38" src="https://user-images.githubusercontent.com/8401092/29262938-fb7ff2ba-80d6-11e7-898f-619478c44a26.png">

**Comment by dmo-odoo** [comment]
Well, this is new then. It removes the need for the no-title-bar package, which incidentally resolves my issue. Thank you very much, this is perfect !
![screen shot 2017-08-14 at 11 34 19](https://user-images.githubusercontent.com/8427726/29266285-8b32f68e-80e4-11e7-8716-80718818168d.png)

**Comment by fv0** [comment]
You’re welcome.
