### ISSUE TITLE
The background of an empty pane isn’t vibrant when focused

### ISSUE THREAD

**Issue by j-f1** [fv0/native-ui#75]
Currently, the background of a focused `atom-pane` element is overridden:

https://github.com/fv0/native-ui/blob/2cc9f49460989ea145fb46deab76754100d8a7fa/styles/panes.less#L9-L11

It looks like an override should be added here to prevent this:

https://github.com/fv0/native-ui/blob/2cc9f49460989ea145fb46deab76754100d8a7fa/styles/atom.less#L3-L8

**Comment by fv0** [comment]
Hi @j-f1, thanks for pointing this out. This is actually the same behavior as in the Finder and is intended to be like this.
