### ISSUE TITLE
Middle click no longer works to close tabs with flexible tabs off

### ISSUE THREAD

**Issue by SarenCurrie** [fv0/native-ui#76]
As of 0.23.0 or Atom 1.19.5, middle mouse no longer closes tabs when flexible tabs is not enabled.

**Comment by SarenCurrie** [comment]
This was fixed by updating atom to 1.19.7

**Comment by fv0** [comment]
@SarenCurrie Thanks for keeping track of this, I couldn’t find a solution for it at the moment.
