### ISSUE TITLE
High cpu load when transparency is enabled

### ISSUE THREAD

**Issue by lexicalunit** [fv0/native-ui#77]
I'm not sure if this is something you can address at the theme level or not but I figured I might as well report it. I had to disable transparency because it was very heavily taxing my cpu, causing my laptop's fans to spin up to full speed whenever I had Atom running. It doesn't seem to matter if I'm even using Atom, just having it running was enough.

It does look really nice tho! Hoping there's something that can be done about it 🤞

**Comment by fv0** [comment]
That’s why I added a checkbox in the Theme settings where you can deactivate it (restart Atom to see it in action). Does that help with the CPU load?

**Comment by lexicalunit** [comment]
Correct. Disabling the feature does resolve the issue of high cpu load. I was hoping there might be additional work that could allow the feature to remain enabled yet also resolve the cpu load issue. Like I said tho, it may not be possible at the theme level.

**Comment by fv0** [comment]
> […] it may not be possible at the theme level.

I think so as well. If somebody knows different, please open a new issue here.
