### ISSUE TITLE
Scrollbar over tab section

### ISSUE THREAD

**Issue by adruiza** [fv0/native-ui#79]
I've noticed that with many tabs opened, there comes a moment when tabs do not resize but instead you are able to scroll horizontally through them. This is consistent with other themes.

But, in this theme, a scrollbar appears bellow when this happens, making it difficult to see the titles or even click a tab, like so:

<img width="882" alt="problem_description" src="https://user-images.githubusercontent.com/9105693/30240819-d49cf6a6-9577-11e7-853d-a638d89fddc7.png">

I think this is not supposed to happen, tested One Dark theme and there's no scrollbar, even though you can do the scrolling. I've the "flexible tabs" settings enabled, if that gives you more info.

Thanks for the theme btw!

**Comment by fv0** [comment]
@haidran Testing a pull request from @hferrier at the moment. Will push it soon for you to update. :-)

**Comment by adruiza** [comment]
Seems to be fixed now, closing. Thank you 😄
