### ISSUE TITLE
Tooltips pop-under dock resize handle

### ISSUE THREAD

**Issue by lexicalunit** [fv0/native-ui#84]
Noticed this today for the first time. The dock handle seemed to be on top of the tooltips from status bar items.

![screen shot 2017-11-09 at 3 15 22 pm](https://user-images.githubusercontent.com/1903876/32630107-1505ce2a-c561-11e7-9ec2-6d0bfc38588b.png)

I made sure to comment out everything in my `styles.less` file first before making this screenshot. Also confirmed that the issue isn't present in some other themes, like Atom One for example.

**Comment by fv0** [comment]
This seems to be related to #82.
