### ISSUE TITLE
Top of tree view is fully transparent on hidden title bar

### ISSUE THREAD

**Issue by seankwalker** [fv0/native-ui#85]
When transparency is enabled and Title Bar is set to hidden in Atom's Core settings, the top of the tree view is fully transparent, as below:

<img width="458" alt="screen shot 2017-11-12 at 17 53 27" src="https://user-images.githubusercontent.com/20524136/32704431-da12ce48-c7d2-11e7-977e-328451866577.png">

I know the settings page says that the hidden title bar option is experimental, so maybe this will be fixed on their end / isn't a possible fix? But I just thought I'd let it be known

**Comment by fv0** [comment]
Thanks for mentioning this. I recommend to use Native UI with a visible title bar though.
