### ISSUE TITLE
@button-background-color-selected not defined

### ISSUE THREAD

**Issue by McCrisp** [fv0/native-ui#86]
> variable @button-background-color-selected is undefined in .atom/packages/atom-ide-ui/modules/nuclide-commons-ui/styles/Table.less:112:16

Got this after the last update. Did you by any chance remove it when cleaning up?
The developers of Atom IDE UI says its a problem with the themes people are using, and not something they should fix.

**Comment by datiecher** [comment]
For more information on the issue: facebook-atom/atom-ide-ui#14

**Comment by fv0** [comment]
@McCrisp Just published a patch for this. This should now work again and not display an error. @datiecher, thanks for the info!
