### ISSUE TITLE
macOS transparency feature doesn't work for me

### ISSUE THREAD

**Issue by gobijan** [fv0/native-ui#89]
Hi, first of all nice theme!
I was astonished that it now seems to be possible enable macOS transparency in themes. Unfortunately it doesn't work for me.

I installed the theme, restarted Atom and set the checkbox to true.
I'm running macOS High Sierra 10.13.4 on an iMac Pro.
Any ideas what could be the issue?

**Comment by davidbwaters** [comment]
Try changing the title bar setting to custom, inset, or hidden in general settings pane

**Comment by jayporta** [comment]
@gobijan Check Atom's stylesheet (Menu bar > Atom > Stylesheet...) and make sure the .tree-view rule is commented out.

**Comment by fv0** [comment]
@gobijan Did the above comments help you?

**Comment by gobijan** [comment]
I did a clean install of Atom (deleting application support etc.) and it now works. I'll close the issue. Thx for your help.
