### ISSUE TITLE
Find in Files has lots of heavy horizontal lines in Atom 1.28

### ISSUE THREAD

**Issue by swrobel** [fv0/native-ui#91]
Previously (Atom 1.27.2 / find-and-replace 0.215.9)
<img width="329" alt="screen shot 2018-06-25 at 6 37 13 pm" src="https://user-images.githubusercontent.com/157270/41884154-ef8fdff6-78a6-11e8-9428-6142d8d47b29.png">

Currently (Atom 1.28.0 / find-and-replace 0.215.11)
<img width="324" alt="screen shot 2018-06-25 at 6 33 07 pm" src="https://user-images.githubusercontent.com/157270/41884163-fd082de6-78a6-11e8-8362-a921600b7af9.png">

**Comment by fv0** [comment]
Should be better now.

![image](https://user-images.githubusercontent.com/8401092/43472173-20449314-94ed-11e8-93a9-bb9dce5bcfd0.png)
