### ISSUE TITLE
OSX mojave: Black text on sidebar is not always easily visible when when macOS transparancy is enabled.

### ISSUE THREAD

**Issue by joelangford** [fv0/native-ui#94]
<img width="1280" alt="screenshot 2018-10-26 at 18 10 24" src="https://user-images.githubusercontent.com/12081900/47581861-90814b80-d94a-11e8-97b4-660b75781f40.png">

Since updating to Mojave the sidebar has lost it's white transparent tint and gone to just a fully transparent tint. When using darker wallpapers it can make the text harder to read as illustrated.

**Comment by johngeorgewright** [comment]
I'm also experiencing this... even when I try and turn off the "macOS transparency" option.

**Comment by fv0** [comment]
Should be fixed with [latest release](https://github.com/fv0/native-ui/releases/tag/v0.27.0).
