### ISSUE TITLE
Feature request: option to have the Tab close button on the right side

### ISSUE THREAD

**Issue by lucasvieites** [fv0/native-ui#97]
Hi,
I'd like to have the close tab button on the right side of the tab. Is it possible to add this as a setting?
Thank you in advance,
Lucas

**Comment by fv0** [comment]
Hi @lucasvieites, thanks for your request. This would go against the native look of tabs in macOS, so I won’t open up this option. If you fiddle around with the CSS of the theme, I’m sure you can position it on the other side, if that’s more valuable to you.

**Comment by lucasvieites** [comment]
Thanks for your update. Of course, and I have actually already done that, but now I have to keep my changes in sync with your future releases :(
I thought I'd add it as a request in case other users would find it useful.

Kind regards,
Lucas
