### ISSUE TITLE
Listing your package on Pulsar

### ISSUE THREAD

**Issue by confused-Techie** [fv0/native-ui#99]
Hello, this is confused-Techie from the Pulsar Team.

[Pulsar](https://github.com/pulsar-edit/pulsar) is an actively developed fork of Atom and one of our major efforts is to preserve the ecosystem of [Community Packages](https://web.pulsar-edit.dev/) that were previously published on Atom.io

While we want to list every single package that existed on Atom's Package Repository, we wanted to respect the license of each package within and ensure to only list packages that either the author has agreed for us to or packages that have a license that specify that redistribution is okay.

That is exactly why we are contacting you today, it seems your package `native-ui` has a license that makes it hard for us to determine if we should be listing it for redistribution.

All that needs to happen for you as a package maintainer is for you to give authorization for us to list your package. Just reply to this issue either way and we will respect your wishes.

Otherwise within 3 weeks, if there is no response, we will assume the answer is no and remove your package from the Pulsar Package Registry.

And if you've missed the deadline we have and still want your package to be published, feel free to [republish to Pulsar](https://pulsar-edit.dev/docs/launch-manual/sections/core-hacking/#publishing).

Thanks a ton for your time, hope you have a great day!

**Comment by fv0** [comment]
You can publish native-ui with Pulsar. Happy if somebody is still using it!

**Comment by confused-Techie** [comment]
> You can publish native-ui with Pulsar. Happy if somebody is still using it!

Thanks a ton for responding so quickly!

I'll note that down on our side and hope you have a fantastic day!

---

But also just to let you know, while I can't see how many new downloads you've received, I can tell you the last time someone downloaded your package from Pulsar seems to be 2 days ago, so still going strong!
